### ISSUE TITLE
Python练习题可以开发吗？

### ISSUE THREAD

**Issue by AndersonHJB** [xjq7/runcode#15]
Python练习题可以开发吗？

**Comment by xjq7** [comment]
@AndersonHJB 可以的, 是什么样的题目呢, 像算法题这种固定输入输出的是比较好做的

**Comment by AndersonHJB** [comment]
选择题、填空题、算法固定的输出结果判断估计会比较好做。

**Comment by xjq7** [comment]
@AndersonHJB 可以开发一些编程题, 类似于我现在开发的前端编程题这种

**Comment by AndersonHJB** [comment]
yes
编程题也不错，最后判断输出结果和答案的结果是否相同

**Comment by xjq7** [comment]
@AndersonHJB 你是做少儿编程教育使用吗
