### ISSUE TITLE
点击运行，提示网络错误

### ISSUE THREAD

**Issue by haolixu** [xjq7/runcode#17]
![image](https://user-images.githubusercontent.com/26183306/224618683-4d786800-2389-4129-9540-9bc3d351cbda.png)

**Comment by xjq7** [comment]
@haolixu 你是启动的生产环境吗, pnpm prod

**Comment by xjq7** [comment]
@haolixu 本地跑生产的话 跑 pnpm prod 跟 pnpm build:tailwind:watch 即可, 跑开发环境 需要启动 server

**Comment by haolixu** [comment]
我是这样运行的，这是server端：
![image](https://user-images.githubusercontent.com/26183306/224932171-02bda9b7-2dce-496c-ad59-f4b28f8a4b14.png)
这是客户端：
![image](https://user-images.githubusercontent.com/26183306/224932435-4bb31cfb-91a9-4299-9adf-1fbccf880449.png)

**Comment by haolixu** [comment]
我mysql和redis都装了。远程也可以连接，就是提示网络错误。。。

**Comment by xjq7** [comment]
@haolixu server 运行的 终端有报错提示吧

**Comment by haolixu** [comment]
我这次 不远程执行，直接在虚拟机上面访问，报错不一样
![image](https://user-images.githubusercontent.com/26183306/224958560-af1501c7-54dc-4d76-9e22-3feec1873da0.png)

**Comment by xjq7** [comment]
@haolixu docker 访问失败, 端口检查下
