### ISSUE TITLE
前端编程题怎么加载？

### ISSUE THREAD

**Issue by xukai504087493** [xjq7/runcode#18]
<img width="651" alt="1" src="https://user-images.githubusercontent.com/6873069/227413876-7438c3c5-4599-45f1-93e0-ac94cfae39b2.png">
感谢作者的分享，已star。
如上图显示
mysql和redis都启动了，数据库里的表也建好了，可以正常运行代码了
但是无法访问题库里的题目
请问怎么配置题库文件夹“question”？

**Comment by xjq7** [comment]
@xukai504087493 sql 结构有问题, 现在更新了, 编程题添加指南在文档也加上了 https://github.com/xjq7/runcode#%E5%88%9B%E5%BB%BA%E9%A2%98%E7%9B%AE, 你试试
