### ISSUE TITLE
建议修改一下文案位置，在侧边栏访问不是很友好

### ISSUE THREAD

**Issue by buildyuan** [xjq7/runcode#19]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/31715808/228111906-4df1cbc8-d21a-4846-9f2b-02c4f1629a33.png">

如图所示：把文案放在底部会不会好一些？

**Comment by xjq7** [comment]
@buildyuan 移动端后面没兼容了, 这个可以改改, 放底部或者移动端收缩都可以

**Comment by xjq7** [comment]
@buildyuan 移动端隐藏了

**Comment by buildyuan** [comment]
> @buildyuan 移动端隐藏了

我尝试了一下，用移动端打开的确没有了，很棒。
但是我的使用场景是 Microsoft Edge for Mac，把网站放在了侧边栏配合使用，所以实际上我的浏览器UA不是移动端，不能实现自动隐藏。

所以，能否根据当前页面的宽度来判断呢？

**Comment by xjq7** [comment]
@buildyuan 感谢建议， 现在调整成宽度判断了
