### ISSUE TITLE
docker 容器配置问题

### ISSUE THREAD

**Issue by Caladog** [xjq7/runcode#27]
请问 “ 前置条件, 安装了 docker, docker 需要设置端口 为 2375”

应该如何配置？
这个2375 是主机的端口？
如果我运行一个 C++的镜像，又配置一个python的镜像，应该如何配置？

**Comment by xjq7** [comment]
在配置文件里 ExecStart=/usr/bin/dockerd 这串后面加上 -H tcp://0.0.0.0:2375 , 然后重启 docker
我是 centos 7 ，我的配置文件在 /usr/lib/systemd/system/docker.service 这个路径

配置文件示例
![image](https://github.com/xjq7/runcode/assets/42568663/42c23ff1-a502-46a0-81a0-05cb9f728b02)

**Comment by Caladog** [comment]
收到，谢谢您，
我试试看。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjq7/runcode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjq7/runcode] docker 容器配置问题 (Issue #27)





 
在配置文件里 ExecStart=/usr/bin/dockerd 这串后面加上 -H tcp://0.0.0.0:2375 , 然后重启 docker
 我是 centos 7 ，我的配置文件在 /usr/lib/systemd/system/docker.service 这个路径
 
配置文件示例
 image.png (view on web)

**Comment by xjq7** [comment]
镜像构建都是独立的，你是想运行 C++ 跟 python 这两种语言吧
 我的项目类已经有配置，你分别进入 server/src/docker/cpp 跟 server/src/docker/python3 目录下，构建下镜像就行了

**Comment by Caladog** [comment]
我感觉镜像我已经构建好了，但是运行不起来。










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjq7/runcode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjq7/runcode] docker 容器配置问题 (Issue #27)





 
镜像构建都是独立的，你是想运行 C++ 跟 python 这两种语言吧
 我的项目类已经有配置，你分别进入 server/src/docker/cpp 跟 server/src/docker/python3 目录下，构建下镜像就行了

**Comment by xjq7** [comment]
看看错误信息

**Comment by Caladog** [comment]
![image](https://github.com/xjq7/runcode/assets/30135964/5abaa1d5-5024-4465-8f78-3028db5031a9)
感谢 @xjq7  大佬，我已经调好了，继续研究。
