### ISSUE TITLE
输出中文乱码

### ISSUE THREAD

**Issue by bh3hbr** [xjq7/runcode#29]
![Uploading iShot_2024-03-28_11.37.46.png…]()

**Comment by Only-silence** [comment]
using System;
namespace CodeApplication
{
    class Code
    {
      static void Main(string[] args)
      {
          Console.WriteLine("你好");
      }
    }
}

**Comment by bh3hbr** [comment]
```
using System;
namespace CodeApplication
{
    class Code
    {
      static void Main(string[] args)
      {
          Console.WriteLine("你好");
      }
    }
}
```

**Comment by xjq7** [comment]
@Only-silence 
using System;
namespace CodeApplication
{
    class Code
    {
      static void Main(string[] args)
      {
          // 这行代码解决中文打印乱码问题
          Console.OutputEncoding = System.Text.Encoding.UTF8;
          Console.WriteLine("你好");
      }
    }
}
添加一行编码设置可以解决乱码问题
