### ISSUE TITLE
控制台程序那样即时的输入输出有办法做到吗

### ISSUE THREAD

**Issue by dalizhushi** [xjq7/runcode#32]
控制台程序那样即时的输入输出有办法做到吗

**Comment by xjq7** [comment]
理论上是可以的, 不过你是什么样的场景呢

**Comment by dalizhushi** [comment]
谢谢解惑，我们想做的就是把输入输出变成控制台一样即时的，来回输入





ys
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjq7/runcode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjq7/runcode] 控制台程序那样即时的输入输出有办法做到吗 (Issue #32)





 
理论上是可以的, 不过你是什么样的场景呢

**Comment by dalizhushi** [comment]
就比如请输入：a

**Comment by dalizhushi** [comment]
输入a之后，
显示下一行，请输入：b
这样
就跟控制台的交互一样了

**Comment by dalizhushi** [comment]
用exec发送命令，好像是做不到，害

**Comment by xjq7** [comment]
前后端通信走 websocket，docker 容器里继续发送输入，输出需要处理下

**Comment by dalizhushi** [comment]
谢谢大佬

**Comment by dalizhushi** [comment]
不好意思，再打扰一下，目前能做到的是跟docker容器进行交互，按我之前说的其实是跟容器里面启动的进程进行交互，像docker api 提供的exec这种方法，是不是做不到啊 “(>_<)”

**Comment by xjq7** [comment]
能做到
