### ISSUE TITLE
打印任意JSON字符串时，输出错误

### ISSUE THREAD

**Issue by sunfkny** [xjq7/runcode#4]
打印 `{}` 输出`[object Object]`
打印 `[1, 2, 3]` 输出 `1,2,3`

**Comment by xjq7** [comment]
@sunfkny 是哪个语言的输出

**Comment by sunfkny** [comment]
> @sunfkny 是哪个语言的输出

每一种语言，只要内容能被 JSON.parse() ，就一定是错误的结果

**Comment by sunfkny** [comment]
> @sunfkny 是哪个语言的输出

https://github.com/xjq7/runcode/blob/d5a45d905b52995bf791484cfb2b6acbe9889dc3/server/src/docker/index.ts#L148 似乎是这里toString导致的
```
Welcome to Node.js v16.10.0.
Type ".help" for more information.
> {}.toString("utf-8")
'[object Object]'
> [1,2,3].toString("utf8")
'1,2,3'
>
```

**Comment by xjq7** [comment]
@sunfkny 是 toString 导致的, []、{} 的 toString 输出正是这样

**Comment by xjq7** [comment]
@sunfkny 这个问题我修复了, 对这两种类型做序列化不走 toString
https://github.com/xjq7/runcode/blob/main/server/src/docker/index.ts#L211
前面也判断了，Buffer 的时候才会 toString
https://github.com/xjq7/runcode/blob/main/server/src/docker/index.ts#L155
感谢指正

**Comment by xjq7** [comment]
问题已修复
